import type { Metadata } from "next";
import "./globals.css";
import { ThemeWrapper } from "@/lib/themeWrapper";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Sidebar from "@/components/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body suppressHydrationWarning>
          <ThemeWrapper
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <nav>
              <Navbar />
            </nav>
            <div>
              <Sidebar />
            </div>
            <main>{children}</main>
          </ThemeWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
